#!/usr/bin/env python3
"""Generate BAS-006 baseline report by running the workspace quality gate."""

import json
import os
import platform
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REPORT_DIR = REPO / "target" / "reports" / "baseline"

GATE_COMMANDS = [
    ("fmt", ["cargo", "fmt", "--all", "--", "--check"]),
    ("clippy", ["cargo", "clippy", "--workspace", "--all-targets", "--", "-D", "warnings"]),
    ("nextest", ["cargo", "nextest", "run", "--workspace"]),
    ("buf_format", ["buf", "format", "--diff", "--exit-code"]),
    ("buf_lint", ["buf", "lint"]),
    ("deny", ["cargo", "deny", "check"]),
]


def run(name, cmd):
    print(f"[{name}] $ {' '.join(cmd)}", flush=True)
    start = time.time()
    result = subprocess.run(
        cmd,
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    elapsed = time.time() - start
    print(f"[{name}] exit={result.returncode} in {elapsed:.2f}s", flush=True)
    return {
        "name": name,
        "command": " ".join(cmd),
        "returncode": result.returncode,
        "elapsed": elapsed,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


def main():
    commit = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=REPO, capture_output=True, text=True
    ).stdout.strip()
    commit_dir = REPORT_DIR / commit
    commit_dir.mkdir(parents=True, exist_ok=True)

    env = {
        "commit": commit,
        "toolchain": "1.96.1",
        "edition": "2024",
        "resolver": "3",
        "host": platform.node(),
        "os": platform.platform(),
        "arch": platform.machine(),
        "cpus": os.cpu_count(),
        "datetime_utc": datetime.now(timezone.utc).isoformat(),
    }

    results = []
    for name, cmd in GATE_COMMANDS:
        results.append(run(name, cmd))

    summary = {
        "environment": env,
        "results": [
            {
                "name": r["name"],
                "command": r["command"],
                "returncode": r["returncode"],
                "elapsed": r["elapsed"],
            }
            for r in results
        ],
    }
    (commit_dir / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    for r in results:
        (commit_dir / f"{r['name']}.stdout.txt").write_text(r["stdout"], encoding="utf-8")
        (commit_dir / f"{r['name']}.stderr.txt").write_text(r["stderr"], encoding="utf-8")

    passed = sum(1 for r in results if r["returncode"] == 0)
    failed = [r["name"] for r in results if r["returncode"] != 0]

    md_lines = [
        f"# BAS-006: Baseline Report ({commit})\n\n",
        f"- Date: {env['datetime_utc']}\n",
        f"- Toolchain: Rust {env['toolchain']}, Edition {env['edition']}, Resolver {env['resolver']}\n",
        f"- Host: {env['host']} ({env['os']}, {env['arch']}, {env['cpus']} CPUs)\n\n",
        "## Quality Gate Results\n\n",
        f"- Passed: {passed}/{len(results)}\n",
        f"- Failed: {', '.join(failed) if failed else 'none'}\n\n",
        "| Gate | Command | Exit | Elapsed |\n",
        "|------|---------|------|----------|\n",
    ]
    for r in results:
        status = "PASS" if r["returncode"] == 0 else "FAIL"
        md_lines.append(
            f"| {r['name']} | `{r['command']}` | {status} ({r['returncode']}) | {r['elapsed']:.2f}s |\n"
        )

    md_lines.append("\n## Notes\n\n")
    md_lines.append("- Raw command outputs are in `target/reports/baseline/{commit}/`.\n")
    md_lines.append("- This report is generated by `scripts/generate_baseline_report.py`.\n")

    md_path = commit_dir / "baseline_report.md"
    md_path.write_text("".join(md_lines), encoding="utf-8")

    sanitized = REPO / "dev-docs" / "003_next_round_vibe_coding_plan" / "reports" / "bas-006-baseline-report.md"
    sanitized.parent.mkdir(parents=True, exist_ok=True)
    sanitized.write_text("".join(md_lines), encoding="utf-8")

    print(f"\nRaw reports: {commit_dir}")
    print(f"Sanitized report: {sanitized}")

    if failed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
